### PR TITLE
feat: 🔥 update CRA

### PR DESCRIPTION
**Pull request by melMass**
* Generate Source Map must be off (cf facebook/create-react-app#11767)
* The craco config should be the bare minimum to polyfill the lib used.
* Move some deps to devDependencies

### CODE REVIEW

**Comment by melMass** [comment]
Also added deploy to gh-pages 🤷‍♂️

**Comment by jagracar** [comment]
Thank you!

**Review by jagracar — COMMENTED** [review]
All looks good and complicated to me! XD

**Review by jagracar — APPROVED** [review]
All good!

**Comment by melMass** [comment]
> All looks good and complicated to me! XD

Yeah I went the rabbit hole so I can sum it up:

A lot of library used in browsers are polymorphic (node + web) but definitely not all library maintainers are actually packaging them properly and webpack4 lead to this bad habit staying like that as it was auto polyfilling those node libs to work in the browser. Since webpack 5 (needed for the new CRA) polyfills are not done automatically (for now, it's being discussed apparently) so here the craco config, subtitutes those imports with browser polyfilled versions

**Comment by jagracar** [comment]
Thank you for the explainer too!

**Pull request merged**
